{colors}: ''
  ###############################################################
  # A skin for a terminal with a dark background
  #
  # This skin is automatically generated from the global nix colorscheme
  # Do not edit this file directly - edit the nix colorscheme instead
  #
  # Doc at https://dystroy.org/broot/skins/
  ###############################################################

  ###############################################################
  # Skin
  # Colors are automatically mapped from the global colorscheme
  ###############################################################
  skin: {
      default: gray(22) none
      tree: gray(8) None
      parent: gray(18) None
      file: gray(22) None
      directory: Blue None bold
      exe: Cyan None
      link: Magenta None
      pruning: gray(12) None Italic
      perm__: gray(5) None
      perm_r: Blue None
      perm_w: Yellow None
      perm_x: Green None
      owner: gray(18) None
      group: gray(15) None
      count: gray(18) gray(4)
      dates: gray(15) None
      sparse: Yellow None
      content_extract: Green None
      content_match: Blue None
      device_id_major: gray(18) None
      device_id_sep: gray(10) None
      device_id_minor: gray(18) None
      git_branch: Yellow None
      git_insertions: Green None
      git_deletions: Red None
      git_status_current: gray(5) None
      git_status_modified: Green None
      git_status_new: Blue None bold
      git_status_ignored: gray(17) None
      git_status_conflicted: Red None
      git_status_other: Red None
      selected_line: None gray(6)
      char_match: Green None
      file_error: Red None
      flag_label: gray(15) gray(2)
      flag_value: Yellow gray(2) bold
      input: White gray(2)
      status_error: gray(22) Red
      status_job: Yellow gray(5)
      status_normal: gray(20) gray(4)
      status_italic: Yellow gray(4)
      status_bold: Yellow gray(4) bold
      status_code: gray(22) gray(4)
      status_ellipsis: gray(19) gray(1)
      purpose_normal: gray(20) gray(2)
      purpose_italic: Yellow gray(2)
      purpose_bold: Yellow gray(2) bold
      purpose_ellipsis: gray(20) gray(2)
      scrollbar_track: gray(7) None
      scrollbar_thumb: gray(22) None
      help_paragraph: gray(20) None
      help_bold: Yellow None bold
      help_italic: gray(22) None
      help_code: gray(21) gray(3)
      help_headers: Yellow None
      help_table_border: gray(15) None
      preview: gray(20) gray(1)
      preview_title: gray(23) gray(2)
      preview_line_number: gray(12) gray(3)
      preview_separator: gray(5) None
      preview_match: None Green
      hex_null: gray(8) None
      hex_ascii_graphic: gray(18) None
      hex_ascii_whitespace: Yellow None
      hex_ascii_other: Yellow None
      hex_non_ascii: Red None
      staging_area_title: gray(22) gray(2)
      mode_command_mark: gray(5) Red bold
      good_to_bad_0: Green
      good_to_bad_1: Green
      good_to_bad_2: Green
      good_to_bad_3: Green
      good_to_bad_4: Green
      good_to_bad_5: Yellow
      good_to_bad_6: Yellow
      good_to_bad_7: Yellow
      good_to_bad_8: Red
      good_to_bad_9: Red
  }

  ###############################################################
  # Syntax Theme
  #
  # Using MochaDark to complement the dark theme
  ###############################################################
  syntax_theme: MochaDark
''
